channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pip>=22.0
      - rpaframework==11.4.2
      - pandas
      - selenium
      - urllib3
      - openpyxl
      - requests
      - beautifulsoup4
      - lxml
      - pillow
